version: '3'

services:
  db1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge